#!/usr/bin/env python3
"""build_evergaol_wake_entities.py — emit the per-map entity-id list of
Evergaol bosses for the proximity-wake emevd patch to consume.

Why this exists
---------------
patch_proximity_wake (emevd_patch.py) wakes bosses two ways: an encounter
scan over $InitializeCommonEvent(0, 90015000/07/21, ...) and a JSON pass that
unions data/fragile_slot_entities.json + data/nr_boss_slots.json. The Evergaol
encounter event (90015026) is deliberately OUT of the encounter scan — it is a
multi-chr arena event whose chr arg is sometimes an entity GROUP, the same
brittleness build_fragile_slot_entities.py was written to dodge — so Evergaol
bosses only get woken if they happen to land in one of the two JSON catalogs.
Auditing the corpus, they don't all: of the 41 Evergaol Enemy Parts, a chunk
sit in NEITHER fragile_slot_entities nor nr_boss_slots, so they freeze (no
EnableCharacterAI ever issues for them).

Unlike fragility, "is this slot an Evergaol" is not an MSB-native bit — it is
the slot's source variant-name marker — so this generator reads the committed
data/nr_slot_inventory.json (itself dumped from the MSB corpus) rather than
re-walking the MSBs. Every Evergaol slot already carries a real entity id (the
46x00800 boss-anchor family), so NO entity-id stamping is involved here; this
is pure catalog inclusion. (Stamping is a separate mechanism for the
entity_id==0 name-marker boss slots elsewhere.)

The output, evergaol_wake_entities.json, is a third {map_stem: [entity_id, ...]}
catalog the proximity-wake JSON pass unions in. The per-entity guards there
dedup against the encounter scan and the other two catalogs, so listing all 41
(not just the currently-uncovered subset) is safe and idempotent — it makes
"every Evergaol boss is woken" an explicit, diffable invariant rather than an
accident of which slots the other catalogs happen to include.

Usage
-----
    python dev/build_evergaol_wake_entities.py [-o OUT.json]
        [--inventory data/nr_slot_inventory.json]

This is a dev/diagnostic tool. It reads only the committed inventory JSON; it
imports nothing from the project root and needs no MSB corpus.
"""

import argparse
import json
import os
import sys

# Variant-name markers that denote an Evergaol slot. Substring, case-folded.
EVERGAOL_MARKERS = ('evergaol',)


def _project_root():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _stem(map_name):
    """Strip a trailing .msb so keys match the EMEVD file stem the patch sees."""
    return map_name[:-4] if map_name.endswith('.msb') else map_name


def build(inventory_path):
    """Read the slot inventory, select Evergaol Enemy Parts with a real entity
    id, and return the result dict ({map_stem: sorted([eid, ...])} + _meta)."""
    with open(inventory_path, encoding='utf-8') as f:
        inv = json.load(f)
    rows = inv if isinstance(inv, list) else next(
        v for k, v in inv.items() if k != '_meta')

    per_map = {}
    total = with_id = no_id = 0
    for s in rows:
        name = (s.get('source_variant_name') or '').lower()
        if not any(mk in name for mk in EVERGAOL_MARKERS):
            continue
        total += 1
        eid = s.get('entity_id') or 0
        if eid in (0, 0xFFFFFFFF):
            # An Evergaol slot with no entity id can't be woken by a per-entity
            # handler — it would need stamping (separate mechanism). Counted,
            # not emitted.
            no_id += 1
            continue
        with_id += 1
        per_map.setdefault(_stem(s['map']), set()).add(eid)

    per_map = {m: sorted(s) for m, s in sorted(per_map.items())}
    return {
        '_meta': {
            'description': 'Per-map entity ids of Evergaol bosses, for the '
                           'proximity-wake emevd patch. The Evergaol encounter '
                           'event (90015026) is excluded from the patch\'s '
                           'encounter scan, and these eids are not all in '
                           'fragile_slot_entities.json / nr_boss_slots.json, so '
                           'without this catalog those bosses never get an '
                           'EnableCharacterAI. Generated by '
                           'dev/build_evergaol_wake_entities.py from '
                           'nr_slot_inventory.json. Pure catalog inclusion — '
                           'every Evergaol slot already has an entity id, so no '
                           'stamping is involved.',
            'source': os.path.basename(inventory_path),
            'evergaol_parts_total': total,
            'evergaol_with_entity_id': with_id,
            'evergaol_no_entity_id': no_id,
            'maps': len(per_map),
            'markers': list(EVERGAOL_MARKERS),
        },
        'evergaol_wake_entities': per_map,
    }


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('-o', '--out', default=None,
                    help='Output JSON path (default: '
                         '<project>/data/evergaol_wake_entities.json).')
    ap.add_argument('--inventory', default=None,
                    help='Path to nr_slot_inventory.json '
                         '(default: <project>/data/nr_slot_inventory.json).')
    ap.add_argument('-q', '--quiet', action='store_true')
    args = ap.parse_args()

    root = _project_root()
    inv = args.inventory or os.path.join(root, 'data', 'nr_slot_inventory.json')
    out = args.out or os.path.join(root, 'data', 'evergaol_wake_entities.json')
    if not os.path.isfile(inv):
        ap.error(f"Inventory not found: {inv}")

    result = build(inv)

    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, 'w', encoding='utf-8') as f:
        json.dump(result, f, indent=2)

    if not args.quiet:
        m = result['_meta']
        print(f"Evergaol parts:            {m['evergaol_parts_total']}")
        print(f"  with entity id (emitted): {m['evergaol_with_entity_id']}")
        print(f"  no entity id (skipped):   {m['evergaol_no_entity_id']}")
        print(f"  maps:                     {m['maps']}")
        for stem, eids in result['evergaol_wake_entities'].items():
            print(f"    {stem}: {len(eids)} eids")
        print(f"\nWrote {out}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
