#!/usr/bin/env python3
"""extract_boss_init_calls.py — derive minimal test-mode EMEVDs by COPYING
the boss-init calls verbatim from vanilla per-map EMEVDs, stripping the
events that disable the boss chr at map-load.

v0.26.1 design (replaces v0.25.x's prefix-based KEEP filter).

The fundamental discovery (May 19 2026)
========================================
Earlier versions assumed vanilla NR boss Parts started DISABLED in the
MSB and were ENABLED by the per-map EMEVD at night-1. Direct comparison
of vanilla witchy'd XMLs to MMV references showed this is wrong:

    | Field                  | Vanilla m48_20 | MMV m46_56  |
    |------------------------|----------------|-------------|
    | GameEditionDisable     | NeverDisable   | NeverDisable|
    | MapStudioLayer         | 4294967295     | 4294967295  |
    | Condition1 / Condition2| 0 / 0          | 0 / 0       |
    | ChrActivateCondParamID | 0              | 0           |

Vanilla NR boss MSB Parts are STRUCTURALLY IDENTICAL to MMV's
NeverDisable Parts on every "alive at map-load" candidate field.

So where does the vanilla boss-disable come from? Entirely from EMEVD.
Specifically, 90065910 (and its multi-phase variants 90065131, 90065121,
90065050, etc.) call `DisableCharacter(chrEntityId)` at event 0, BEFORE
waiting for the night-1 flag. The chr is alive in the MSB but the
EMEVD immediately disables it at game start.

v0.26.1 strategy
================
Since the MSB is already correct (NeverDisable), the test mode is purely
about stripping the events that disable the chr. The new filter:

  KEEP, by default:
    - 9006xxxx — except events that contain DisableCharacter in their body
      (see DISABLE_CHR_EVENTS below). Notably 90065911 (cleanup) and
      90065900 (post-death enable) are KEPT.
    - 9005xxxx — night-1 flag setter fallback (90055000/001)
    - 9003xxxx — asset toggles tied to night-1
    - 90015002 — combat aggro + healthbar UI when player engages
    - 90015008 — death observer (sets the night-2 cleanup flag)
    - 90015012 — multiplayer combat-scaling SpEffect
    - 90015015/016 — chr SpEffect setters (specific Limveld tiles)
    - 90015020 — multiplayer status flag
    - 90015030 — idle anim
    - 90015442 — PRIMARY night-1 flag setter (tile→arena translator,
      v0.25.10's miss)
    - 90015443 — paired arena flag-setter

  STRIP:
    - All chr-disabler events (DISABLE_CHR_EVENTS set, computed by
      scanning common_func.emevd.js for events whose body contains
      DisableCharacter)
    - 90015070 — cinematic frame triggers (original test-mode goal)
    - Everything else not in the keep set

Result: chr alive at day-1 (MSB NeverDisable, no EMEVD disable), boss
is fightable immediately, on death + night-1-flag the cleanup fires and
night-2 progresses normally. The only behavioral cost vs vanilla is
no "dramatic night-1 appearance" — chr is already standing there. For
test mode that's a feature; iteration is much faster.

Tradeoff worth noting: no boss BGM transition (90065910 set the music),
and boss healthbar visibility depends on 90015002 firing (which it does
when player enters combat range).
"""
from __future__ import annotations

import os
import re
import struct
from dataclasses import dataclass, field
from typing import List, Optional


# v0.26.1: hardcoded list of 9006xxxx events whose body contains
# DisableCharacter. These get STRIPPED from test-mode overlays so the
# chr stays alive from map-load (the MSB Part is already NeverDisable).
# Generated by scanning common_func.emevd.js — regenerate if vanilla
# updates change the event bodies (see _scan_disable_chr_events helper
# at the bottom of this file).
DISABLE_CHR_EVENTS = frozenset({
    90065000, 90065001, 90065002, 90065009, 90065014, 90065031,
    90065040, 90065050, 90065051, 90065052, 90065053, 90065056, 90065057,
    90065061, 90065062, 90065064, 90065070, 90065082, 90065090,
    90065100, 90065110, 90065120, 90065121, 90065122,
    90065130, 90065131, 90065132,
    90065201, 90065211, 90065215, 90065216, 90065220, 90065221,
    90065251, 90065252, 90065254,
    90065910, 90065912,
})

# Events we explicitly KEEP regardless of prefix-based rules.
# 90015002: combat aggro + healthbar UI when player engages
# 90015008: death observer — sets post-kill flag for night-2
# 90015012: multiplayer combat-scaling SpEffect
# 90015015/016: chr SpEffect setters (specific Limveld tiles)
# 90015020: multiplayer status flag
# 90015030: idle anim (cosmetic but cheap)
# 90015442: PRIMARY night-1 flag setter (tile→arena translator).
#           This was the v0.25.10 miss — chain broke because no flag
#           was getting set. Kept now.
# 90015443: paired arena flag-setter
KEEP_EVENT_EXPLICIT = frozenset({
    90015002, 90015008, 90015012, 90015015, 90015016,
    90015020, 90015030, 90015442, 90015443,
})

# Prefix-based keep — keep all 9005xxxx (night-1 flag fallback path)
# and 9003xxxx (asset toggles tied to night-1 progression).
# 9006xxxx is conditionally kept (see _should_keep_event).
KEEP_EVENT_PREFIXES = ('9005', '9003')


def _should_keep_event(event_id: int) -> bool:
    """Return True if the event_id should be preserved in the test-mode EMEVD.

    Rules (in order):
      1. If in DISABLE_CHR_EVENTS — STRIP (these disable the boss chr).
      2. If in KEEP_EVENT_EXPLICIT — KEEP.
      3. If 9006xxxx (and not in DISABLE_CHR_EVENTS by rule 1) — KEEP.
         These are 9006xxxx events that don't disable chrs: 90065911
         (cleanup), 90065900 (post-death), and similar.
      4. If matches a KEEP_EVENT_PREFIXES prefix — KEEP.
      5. Otherwise — STRIP.
    """
    if event_id in DISABLE_CHR_EVENTS:
        return False
    if event_id in KEEP_EVENT_EXPLICIT:
        return True
    eid_str = str(event_id)
    if eid_str.startswith('9006'):
        return True
    for prefix in KEEP_EVENT_PREFIXES:
        if eid_str.startswith(prefix):
            return True
    return False


# ───────────────────────────────────────────────────────────────────


@dataclass
class CallSpec:
    """One InitializeCommonEvent call extracted from vanilla."""
    slot: int       # the first arg to InitializeCommonEvent, usually 0; layer 1 is rare
    event_id: int   # the common_event being called (e.g. 90065910)
    params: List[int]  # the remaining args, verbatim from vanilla

    def emit_text(self) -> str:
        """DarkScript3 source line."""
        all_args = [str(self.slot), str(self.event_id)] + [str(p) for p in self.params]
        return f"$InitializeCommonEvent({', '.join(all_args)});"


@dataclass
class ArenaEmevdSpec:
    """Test-mode EMEVD for one arena.

    Holds just the calls we want to emit, in the order vanilla had them.
    No boss-spec / region-eid structure — we don't transform the call
    args, we copy them verbatim.
    """
    map_short_name: str  # e.g. 'm48_90_00_00'
    calls: List[CallSpec] = field(default_factory=list)


# ───────────────────────────────────────────────────────────────────
# Extraction from vanilla EMEVD source
# ───────────────────────────────────────────────────────────────────


# Match $InitializeCommonEvent(slot, event_id, arg1, arg2, ...);
# Slot can be 0 or 1 (layer marker). Event ID is 6-9 digits.
# Args can be any integers (possibly negative).
_CALL_RE = re.compile(
    r'\$InitializeCommonEvent\s*\(\s*'
    r'(\d+)\s*,\s*'           # slot
    r'(\d+)\s*'                # event_id
    r'((?:\s*,\s*-?\d+(?:\.\d+)?)*)'  # zero or more args (we'll strip .0)
    r'\s*\)\s*;?'
)


def extract_calls(vanilla_emevd_js: str) -> List[CallSpec]:
    """Parse a vanilla per-map EMEVD .js source and return all the
    boss-init / death-observer InitializeCommonEvent calls we want to
    preserve in the test-mode overlay.

    The order is preserved (matches vanilla's emit order).
    """
    out: List[CallSpec] = []
    for m in _CALL_RE.finditer(vanilla_emevd_js):
        slot = int(m.group(1))
        event_id = int(m.group(2))
        if not _should_keep_event(event_id):
            continue
        rest = m.group(3).strip()
        if rest.startswith(','):
            rest = rest[1:]
        params: List[int] = []
        if rest:
            for p in rest.split(','):
                p = p.strip()
                if not p:
                    continue
                # Some args may be floats like 0.55; truncate to int
                # since the EMEVD wire format stores everything as uint32
                # and DarkScript3 emits floats only as a DSL convenience.
                # The bit pattern matters; for InitializeCommonEvent args,
                # vanilla writes them as raw uint32 bits.
                if '.' in p:
                    # Float param — encode bits as uint32 via struct
                    f = float(p)
                    bits = struct.unpack('<I', struct.pack('<f', f))[0]
                    params.append(bits)
                else:
                    n = int(p)
                    if n < 0:
                        # Negative int → two's complement uint32
                        n = n & 0xFFFFFFFF
                    params.append(n)
        out.append(CallSpec(slot=slot, event_id=event_id, params=params))
    return out


# ───────────────────────────────────────────────────────────────────
# Emit — text and binary
# ───────────────────────────────────────────────────────────────────


def emit_text(spec: ArenaEmevdSpec) -> str:
    """Generate a DarkScript3 .emevd.js source for the test-mode EMEVD.

    Single $Event(0, Default, ...) containing all kept calls in order.
    """
    lines = [
        "// ==EMEVD==",
        "// @docs    nr-common.emedf.json",
        "// @compress    DCX_KRAK",
        f"// @generated {spec.map_short_name} test-mode (v0.26.1)",
        f"// {len(spec.calls)} boss-init/death-observer calls preserved from vanilla",
        "// ==/EMEVD==",
        "",
        "$Event(0, Default, function() {",
    ]
    for c in spec.calls:
        lines.append(f"    {c.emit_text()}")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def emit_binary(spec: ArenaEmevdSpec) -> bytes:
    """Generate raw .emevd binary (Sekiro+ format).

    Uses the synth.py builder. The builder accepts any event_id /
    arg-count combination because InitializeCommonEvent is just a
    flat-args record (class=2000, index=0, then N uint32 args).
    """
    import sys
    _here = os.path.dirname(os.path.abspath(__file__))
    _hb_path = os.path.join(_here, '..', 'healthbar_inplace')
    if _hb_path not in sys.path:
        sys.path.insert(0, _hb_path)
    from synth import build_minimal_emevd, healthbar_instruction

    instructions = []
    for c in spec.calls:
        # healthbar_instruction(slot, common_event_id, *params) builds
        # the args list as [slot, common_event_id, *params] and returns
        # an InitializeCommonEvent record. Name is historical (it was
        # built for the healthbar parser test fixtures).
        instructions.append(healthbar_instruction(c.slot, c.event_id, *c.params))

    events_spec = [{
        'event_id': 0,
        'rest_behavior': 0,  # Default
        'instructions': instructions,
    }]
    return build_minimal_emevd(events_spec)


# ───────────────────────────────────────────────────────────────────
# CLI
# ───────────────────────────────────────────────────────────────────


def main():
    import argparse
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--vanilla-emevd-js', required=True,
                     help='Vanilla per-map EMEVD .js source')
    ap.add_argument('--map-name', required=True,
                     help='Map short name (e.g. m48_90_00_00)')
    ap.add_argument('--out-js', help='Write text emit here')
    ap.add_argument('--out-bin', help='Write binary emit here (.emevd, pre-DCX)')
    args = ap.parse_args()

    with open(args.vanilla_emevd_js) as f:
        vsrc = f.read()
    calls = extract_calls(vsrc)
    if not calls:
        print(f'WARNING: no boss-init calls extracted from {args.vanilla_emevd_js}')
    spec = ArenaEmevdSpec(map_short_name=args.map_name, calls=calls)

    print(f'Extracted {len(calls)} calls from {args.vanilla_emevd_js}:')
    for c in calls[:10]:
        print(f'  {c.emit_text()}')
    if len(calls) > 10:
        print(f'  ... +{len(calls)-10} more')

    if args.out_js:
        with open(args.out_js, 'w') as f:
            f.write(emit_text(spec))
        print(f'Text emit -> {args.out_js}')
    if args.out_bin:
        with open(args.out_bin, 'wb') as f:
            f.write(emit_binary(spec))
        print(f'Binary emit -> {args.out_bin}')


def _scan_disable_chr_events(common_func_js_path: str) -> set:
    """Regenerate DISABLE_CHR_EVENTS by scanning common_func.emevd.js.

    Run this if vanilla NR updates change the 9006xxxx event bodies.
    Print the result and paste it into the DISABLE_CHR_EVENTS literal at
    the top of this file.

    Usage:
      python3 -c "from dev.extract_boss_init_calls import _scan_disable_chr_events; \\
                  print(sorted(_scan_disable_chr_events('path/to/common_func.emevd.js')))"
    """
    with open(common_func_js_path) as f:
        src = f.read()
    event_re = re.compile(r'\$Event\((\d+),\s*\w+,\s*function[^)]*\)\s*\{', re.DOTALL)
    out = set()
    for m in event_re.finditer(src):
        eid = int(m.group(1))
        if not 90065000 <= eid <= 90069999:
            continue
        start = m.end()
        depth, i = 1, start
        while i < len(src) and depth > 0:
            if src[i] == '{': depth += 1
            elif src[i] == '}': depth -= 1
            i += 1
        body = src[start:i-1]
        if 'DisableCharacter' in body[:1500]:
            out.add(eid)
    return out


if __name__ == '__main__':
    main()
